config/routes.rb
Opentable::Application.routes.draw do
  
  
  resources :restaurants do
    resources :reservations
  end
  
  resources :users, :only => [:new, :create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurants
	belongs_to :users
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
# 	validates :name, :description => true
	has_many :reservations
	has_many :users, through: :reservations

	def total_seats
		100
	end


	def open_time
		# this should return a DateTime object (10am for example)
	end

	def close_time
		
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations, through: :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show, :new, :edit, :create, :update, :destroy]
  before_filter :load_restaurant

  def index
  	@reservations = Reservation.all
  end

  def show
  	@reservation = Reservation.find(params[:id])
  end

  def new
  	@reservation = Reservation.new
  end

  def edit
  	   @reservation = Reservation.find(params[:id])
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)

  	if @reservation.save
  		redirect_to restaurant_reservations_path(@restaurant)

  	else
  		render :new
  	end
  end

  def update
  	@reservation = Reservation.find(params[:id])

  	if @reservation.update_attributes(reservation_params)
  		redirect_to reservation_path(@reservation)
  	else
  		render :edit
  	end
  end

  def destroy
  	@reservation = Reservation.find(params[:id])
  	@reservation.destroy
  	redirect_to reservations_path
  end

  private

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reservation_params
    params.require(:reservation).permit(:name, :booking_time, :created_at, :updated_at)
  end
  # def booking_time_params
  #   params.require(:booking_time).permit(:datetime)
  # end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_filter :ensure_logged_in, :only => [:new]

  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end

  def create
  	@restaurant = Restaurant.new(restaurant_params)

  	if @restaurant.save
  		redirect_to restaurants_url
  	else
  		render :new
  	end
  end

  def update
  	@restaurant = Restaurant.find(params[:id])

  	if @restaurant.update_attributes(restaurant_params)
  		redirect_to restaurant_path(@restaurant)
  	else
  		render :edit
  	end
  end

  def destroy
  	@restaurant = Restaurant.find(params[:id])
  	@restaurant.destroy
  	redirect_to restaurants_path
  end

  private
  def restaurant_params
  	params.require(:restaurant).permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to restaurants_url, :notice => "You are now logged in"
  	else
      flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to restaurants_url, :notice => "You have been logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to restaurants_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opentable</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>

	<%= yield %>

		<p class="userinfo">
			<% if current_user %>
				Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end %>
		</p>
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant, @reservation]) do |f| %>


	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">		
		<%= f.datetime_select :booking_time  %>
		
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit a Reservation</h1>

<p>
	<%= link_to "Back", restaurant_reservations_path %>
</p>

<%= form_for([@restaurant, @reservation]) do |f| %>


	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">		
		<%= f.datetime_select :booking_time  %>
		
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/reservations/index.html.erb
<h1>Current Reservations</h1>
<center><%= link_to "Make a Reservation", new_restaurant_reservation_path %> | <%= link_to "Back to Restaurants", restaurants_path %>
<% @reservations.each do |p| %>
	<p><li><%= link_to p.name, restaurant_reservation_path(p.restaurant_id, p.id) %> <%= p.booking_time %> </li></p> 
	
<% end %></center>

app/views/reservations/new.html.erb
<h1>New Reservations</h1>

<center><%= render 'form' %>
<%= link_to 'Back', restaurant_reservations_path %></center>

app/views/reservations/show.html.erb
<h1>Current Reservation</h1>
<center><%= link_to "Make a new reservation", restaurants_path %> | <%= link_to "Edit a Reservation", edit_restaurant_reservation_path(@restaurant.id, @reservation.id) %></center>

<center><p><b><%= @reservation[:name] %></b> - <%= @reservation[:booking_time] %> </p></center>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |r| %>
<% if @restaurant.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

		<ul>
		<% @restaurant.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
	<% end %> 
	<div class="field">
		<%= r.label :name %><br />
		<%= r.text_field :name %>
	</div>
	<div class="field">
		<%= r.label :description %><br />
		<%= r.text_area :description %>
	</div>
	<div class="actions">
		<%= r.submit %>
	</div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit a Restaurant</h1>

<p>
	<%= link_to "Back", restaurant_path %>
</p>

<%= form_for @restaurant do |f| %>
	<p>
		<%= f.label "name" %><br>
		</br><%= f.text_field "name" %>
	</p>
	<p>
		<%= f.label "description" %><br>
		</br><%= f.text_area "description" %>
	</p>
	<p>
		<%= submit_tag "Save" %>
	</p>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<p>Select a restaurant to make a reservation. | <%= link_to "Post a New Restaurant", new_restaurant_path %> </p>
<% @restaurants.each do |p| %>
	<center><p><li><%= link_to p.name, restaurant_path(p) %></li></p><center>
<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>
<center><%= render 'form' %>
<%= link_to 'Back', restaurants_path %></center>

app/views/restaurants/show.html.erb
<h1>Restaurants</h1>
<center><%= link_to "Edit Info", edit_restaurant_path %> 
| <%= link_to "Make a Reservation", new_restaurant_reservation_path(@restaurant) %> 
| <%= link_to "See Reservations", restaurant_reservations_path(@restaurant) %> | <%= link_to "Back", restaurants_path %></center>

<p><b><%= @restaurant.name %></b></p>
<p><%= @restaurant.description %></b></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions"><%= f.submit %></div>
<% end %>